name: Linting, etc.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: "**/*.md"

      - name: markdownlint
        run: |
          sudo gem install mdl
          mdl **/*.md
